language: scala

scala:
  - 2.10.7
  - 2.11.12
  - 2.12.6

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

jdk:
  - oraclejdk8

sudo: false

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - wget https://raw.githubusercontent.com/paulp/sbt-extras/3c8fcadc3376e/sbt && chmod +x ./sbt
  - ./sbt ++${TRAVIS_SCALA_VERSION} checkGenerateCodeError compile test:compile scalapropsTestNames scalapropsJS/test scalapropsJVM/test
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
  - if [[ ${JAVA_HOME} == $(jdk_switcher home oraclejdk9) ]]; then rm -rf $HOME/.ivy2/cache ; fi

env:
  global:
  - secure: "RNHbSs1b4iZBg5fhUSjC/bKT7FbcAd6Qy/1892l2lsrlMg/1veVoDDbcQA5GowcfD8GQhjyf21gewSe0J+2V/4w0fN6ASaAfCyeusf+aDEHCDVOrdviUCn5lWclIuMfUU887Y5YIube/ZA1Ra2y1EvpuUTUuyw7bPftumbLk3hKaVwiRHQ0lvaUdJzStP0OdMomFEuThCFv3lnzVyyjn7SPoBtRN+IGJDXGuebvE8KckEtaJR8HQAlJXzZpceox1q2QS5piwtLdXZul2FiUPxRlfn3tZ8cHzmzphv2+JzWQcSF2j4D5E1z9qN5j8Qaw6Z11jCHCZZmbky3BOoirebpTO/AOQwIjvbjBSg/hEv/kTBv0PJJJihN0XzQWa6jYDy5IWzrcWE7lFLqBe26rkBZnxTQpIF0C4OG3UIrfQqLKRel9863Z8uiKFYYvFrpdyE2fBIwTfomVvQqMp6NvqLYrHIrUM/fOmJeeRb43a1HGJdDMxdZrsQxxoqIaXTNdhgL8V3zoEDGYCco4ctzaNld0cIOKR1s1pr0hU+SzrtQ1rqbDeMPcvBChf+SCZ0SV3hFO7xkO8ryIPFqwebm0JY0Ms6Y734jGXF+l7PEWdPVHfAaWh8LBddBccnswW40lUyQIC99QTgbHbeISCcOIeL7ZnYxDOnOP08oMi9UoNYQA="
  - secure: "1nLEUpE0uCYoIQTvjaMIKB7Odv7GwT9RI86y3xVTqrFL0Kqle9z3ggOqxX8ck/ewvAvBdCzgyG33BWL3rLE9LsygAwo5RikC57k1NqEpEsKZpckX17LlWrWBlawLAEELjnOJpCq5EVKhJI7xYpIleyALQFFcxH9oq7yyeJAq/ybxu8SCWlyHYdhXj5nN9nf9bR8Ad5bjJNrPzn8JzjF8eHZnqEDuS09tM8740+07fFP34ZAtBLDnmDWKM7hYrlgctFZASei6rS1a6KuOpze9rhQ3OCQOzQ4dJogaiQwmgC8/EDryvzeTtvj0NbtzZTQYR2peElb5FjCrECOMeT47YRC3xZH8vpcLd3QKHiUrQTfrFgknexyAfSvDQPbAgWA7KTffglm3nBn56OxK8LkZQ1b8CoPP3Eb67YavSBLncQkC3AyEF9zo0Z12Quy4IIB4AjiIApFgAdVP78RbaxzDrz3iBhC8okQXYiWTXRe5THgGW1WyMOcCFF9TcPLz0tyJLkHvcp89NQXdskzvZQmnQWNkmNl8c6VdGZbpHpUIYpNw9VF1sTRqgpP+VQTcTLQNKShvDkRHL7Oot2uOAdJHR/dqKHS9/LaFl4FtJdI9kcCqsptIuQkPiHNhF7m4PuVufkqdWEZz+Qbd3731yv0PzJpkGdE4KloA6NCc/DCJI/0="

matrix:
  include:
    - scala: SCALA_NATIVE
      jdk: oraclejdk8
      sudo: required
      before_install:
      - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
      - wget https://raw.githubusercontent.com/paulp/sbt-extras/3c8fcadc3376e/sbt && chmod +x ./sbt
      script:
      - ./sbt -J-Xmx5G rootNative/compile scalapropsNative/test
    - scala: 2.12.6
      jdk: oraclejdk9
      script:
      - java -version
      - sbt ++$TRAVIS_SCALA_VERSION scalapropsJS/test scalapropsJVM/test
